name: ADF Deployment Workflow

on:
  push:
    branches:
      - adf_publish  # Replace with your branch name where changes trigger deployment

jobs:
  deploy-adf:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Log in to Azure using the Service Principal credentials
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CLIENTID }}
          client-secret: ${{ secrets.CLIENTSECRET }}
          tenant-id: ${{ secrets.TENANTID }}
          subscription-id: ${{ secrets.SUBSCRIPTIONID }}

      # Step 3: Deploy ARM template to Azure Resource Group
      - name: Deploy Azure Data Factory Resources
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.SUBSCRIPTIONID }}
          resourceGroupName: <RESOURCE_GROUP_NAME>  # Replace with your Azure resource group name
          template: './cdhdatafactorydev/ARMTemplateForFactory.json'  # Path to your ARM template file
          parameters: './cdhdatafactorydev/ARMTemplateParametersForFactory.json'  # Path to your ARM parameters file
          deploymentMode: Incremental  # Use Incremental to update existing resources
