name: ADF Deployment Workflow

on:
  push:
    branches:
      - adf_publish  # Replace with your branch name where changes trigger deployment

permissions:
  id-token: write

jobs:
  deploy-adf:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install Az Module (Avoid Conflicts)
      - name: Install Az Module
        run: |
          if (-not (Get-Module -ListAvailable -Name Az)) {
            Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force -AllowClobber
          }
        
      # Step 2: Log in to Azure using the Service Principal credentials
      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
          
      # Step 3: Deploy ARM template to Azure Resource Group

      - name: Deploy ADF Resources
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: CDH_TEST # Replace with your ADF resource group name
          dataFactoryName: cdhdatafactorytest             # Replace with your ADF instance name
          armTemplateFile: cdhdatafactorydev/ARMTemplateForFactory.json
          armTemplateParametersFile: cdhdatafactorydev/ARMTemplateParametersForFactory.json
