name: ADF Deployment Workflow

on:
  push:
    branches:
      - adf_publish  # Replace with your branch name where changes trigger deployment

permissions:
  id-token: write

jobs:
  deploy-adf:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Az Module
        run: |
          if (-not (Get-Module -ListAvailable -Name Az)) {
            Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force -AllowClobber
          }
          
      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
          
      - name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v1.0.6
        with:
          scope: 'resourcegroup'
          resourceGroupName: 'CDH_TEST'
          template: './cdhdatafactorydev/ARMTemplateForFactory.json'
          deploymentMode: Incremental
