name: ADF Deployment Workflow (Manual Trigger)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to (test or prod)'
        required: true
        default: 'test'
        type: choice
        options:
          - test
          - prod

permissions:
  id-token: write

jobs:
  deploy-adf:
    runs-on: windows-latest
    if: github.ref == 'refs/heads/adf_publish'  # Ensure it runs only on the adf_publish branch

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Az Module
        run: |
          if (-not (Get-Module -ListAvailable -Name Az)) {
            Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force -AllowClobber
          }

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Deploy Azure Data Factory
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: ${{ inputs.environment == 'prod' && 'CDH_PROD' || 'CDH_TEST' }}
          dataFactoryName: ${{ inputs.environment == 'prod' && 'cdhdatafactoryprod' || 'cdhdatafactorytest' }}
          armTemplateFile: './cdhdatafactorydev/ARMTemplateForFactory.json'
          armTemplateParametersFile: './cdhdatafactorydev/ARMTemplateParametersForFactory.json'
          additionalParameters: |
            -factoryName=${{ inputs.environment == 'prod' && 'cdhdatafactoryprod' || 'cdhdatafactorytest' }}
            -deployToEnvironment=${{ inputs.environment }}
